---
name: dev124
director_uuid: 60b75ba0-b1dd-4aee-b1f5-ca178b741349 # Change this to the UUID of the BOSH director.
release:                                            # Find this with > bosh status.
  name: bosh # Change this to reflect the name of your release. This is specified in your release manifest.
  version: 5 # Specify the version of your release. This is also specified in your release manifest.

networks:
- name: default # An internal name for the network in your manifest file
  subnets:
  - reserved:
    - 10.1.4.200 - 10.1.4.210 # IP addresses which you don't want allocated by BOSH
    static:
    - 10.1.4.222 - 10.1.4.240 # A static IP range that can be used for deploying BOSH
    range: 10.1.4.0/16        # The range of IP addresses that can be accessible by BOSH
    gateway: 10.1.1.1
    dns:
    - 10.1.1.2
    cloud_properties:
      name: "VM Network"      # The name of the virtual machine network in vCenter

#
# You shouldn't have to change any of the resource pool parameters
#

resource_pools:
- name: small
  stemcell:
    name: bosh-stemcell
    version: 0.5.2
  network: default
  size: 5
  cloud_properties:
    ram: 512
    disk: 2048
    cpu: 1
- name: director
  stemcell:
    name: bosh-stemcell
    version: 0.5.2
  network: default
  size: 1
  cloud_properties:
    ram: 2048
    disk: 8192
    cpu: 2

compilation:
  workers: 6
  network: default
  cloud_properties:
    ram: 2048
    disk: 4048
    cpu: 4

#
# If you have errors with canary instances during a deployment, you can try 
# increasing the canary_watch_time and update_watch_time. The values here are in 
# milliseconds. Divide by 1000 to get the value in seconds.
# 
#

update:
  canaries: 1
  canary_watch_time: 60000
  update_watch_time: 60000
  max_in_flight: 1
  max_errors: 2

jobs:

- name: nats
  template: nats
  instances: 1
  resource_pool: small
  networks:
  - name: default
    static_ips:
    - 10.1.4.222         # Assign a static IP

- name: postgres
  template: postgres
  instances: 1
  resource_pool: small
  persistent_disk: 2048
  networks:
  - name: default
    static_ips:
    - 10.1.4.223        # Assign a static IP from the static range specified above

- name: redis
  template: redis
  instances: 1
  resource_pool: small
  networks:
  - name: default
    static_ips:
    - 10.1.4.224       # Assign a static IP from the static range specified above

- name: director
  template: director
  instances: 1
  resource_pool: director
  persistent_disk: 2048
  networks:
  - name: default
    static_ips:
    - 10.1.4.225      # Assign a static IP from the static range specified above

- name: blobstore
  template: blobstore
  instances: 1
  resource_pool: small
  persistent_disk: 20480
  networks:
  - name: default
    static_ips:
    - 10.1.4.226     # Assign a static IP from the static range specified above

- name: health_monitor
  template: health_monitor
  instances: 1
  resource_pool: small
  networks:
  - name: default
    static_ips:
    - 10.1.4.227    # Assign a static IP from the static range specified above

properties:
  env:

  blobstore:
    address: 10.1.4.226     # This should be the same IP specified for the job above
    port: 25251
    backend_port: 25552
    agent:
      user: agent
      password: 38fh20
    director:
      user: director
      password: oe9U37dbd

  networks:
    apps: default
    management: default

  nats:
    user: nats              
    password: 38dhj389ddck378gcE
    address: 10.1.4.222    # This should be the same IP specified for the job above
    port: 4222

  postgres:
    user: bosh             
    password: 29fhcuebJDldhv265kB
    address: 10.1.4.223   # This should be the same IP specified for the job above
    port: 5432
    database: bosh

  redis:
    address: 10.1.4.224   # This should be the same IP specified for the job above
    port: 25255
    password: wicjew93hf2

  director:
    name: dev124
    address: 10.1.4.225  # This should be the same IP specified for the job above
    port: 25555

  hm:
    http:
      port: 25923
      user: admin
      password: 8wufn
    director_account:
      user: admin
      password: 8wufn
    intervals:
      poll_director: 60
      poll_grace_period: 30
      log_stats: 300
      analyze_agents: 60
      agent_timeout: 180
      rogue_agent_alert: 180
    loglevel: info
    email_notifications: false
    email_recipients:
    - noemail@yourdomain.com
    smtp:
      from: bhm@localhost.localdomain
      host: smtp.yourdomain.com
      port: 25
      auth: plain
      user: appcloud
      password: 38fhsoeY
      domain: localdomain
    tsdb_enabled: false     # If this option is set to false, comment out its params.
    #tsdb:
    #  address: 10.1.4.228
    #  port: 4242

  vcenter:
    address: 10.1.1.3       # The IP of your vCenter server
    user: Administrator     # Your vCenter server user
    password: fyehal82W     # You vCenter user password
    datacenters:
      - name: Dev           # The datacenter name in vCenter
        vm_folder: CF_VMs   # This folder should be created automatically by BOSH
        template_folder: CF_Templates # This folder should be created automatically by BOSH
        disk_path: CF_Disks # Create this path manually in your datastore
        datastore_pattern: 1TB-ISCSI # See the offcial BOSH documentation (documentation.md) for additional pattern params
        persistent_datastore_pattern: 1TB-ISCSI
        allow_mixed_datastores: true # Are you mixing persistent and non-persistent disks?
        clusters:
        - Rubicon:                   # The cluster name
            resource_pool: Bosh      # Manually create this resource pool for BOSH
